services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules