services:
  db:
    container_name: db
    image: "postgres:${POSTGRES_VERSION}"
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:${POSTGRES_PORT}"
    networks:
      - backend

  app:
    container_name: app
    #image: user/app:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - ${PORT_APP}:${PORT_APP}
    depends_on:
      - db
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend: